import { Metadata } from "next";


export const metadata: Metadata = {
  title: "SafeDep",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
        className="bg-[url(/background.png)] bg-no-repeat bg-cover min-h-screen text-white px-24 py-20"
      >
        {children}
      </div>
  );
}
